version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
    networks:
      - microservices-network

  db-cambio:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - cambio_service:/var/lib/mysql
    networks:
      - microservices-network

  db-book:
    image: mysql:8.0.29
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: book-service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - book_service:/var/lib/mysql
    networks:
      - microservices-network

  discovery-server:
    image: matheusslr/discovery-server:0.0.1
    ports:
      - "8761:8761"
    command: mvn spring-boot:run
    networks:
      - microservices-network

  api-gateway:
    image: matheusslr/api-gateway:0.0.1
    ports:
      - "8765:8765"
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://discovery-server:8761/eureka
    command: mvn spring-boot:run
    depends_on:
      - discovery-server
    networks:
      - microservices-network

  cambio-service:
    image: matheusslr/cambio-service:0.0.1
    ports:
      - "8000:8000"
    command: mvn spring-boot:run
    restart: always
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING.DATASOURCE.URL: jdbc:mysql://db-cambio:3306/cambio_service?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.URL: jdbc:mysql://db-cambio:3306/
    depends_on:
      - discovery-server
      - db-cambio
    networks:
      - microservices-network

  book-service:
    image: matheusslr/book-service:0.0.1
    ports:
      - "8100:8100"
    command: mvn spring-boot:run
    restart: always
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING.DATASOURCE.URL: jdbc:mysql://db-book:3307/book-service?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.URL: jdbc:mysql://db-book:3307/book-service?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.PASSWORD: root
    depends_on:
      - discovery-server
      - db-book
      - cambio-service
    networks:
      - microservices-network

volumes:
  cambio_service:
  book_service:

networks:
  microservices-network:
    driver: bridge