version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin:2.23.2
    ports:
      - "9411:9411"
    depends_on:
      - rabbit-mq
    networks:
      - microservices-network
  rabbit-mq:
    image: rabbitmq:3.9.29-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - microservices-network

  db-cambio:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - cambio_service:/var/lib/mysql
    networks:
      - microservices-network

  db-book:
    image: mysql:8.0.29
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
    ports:
      - "3307:3306"
    expose:
      - 3307
    volumes:
      - book_service:/var/lib/mysql
    networks:
      - microservices-network

  discovery-server:
    image: matheusslr/discovery-server:0.0.1
    ports:
      - "8761:8761"
    command: mvn spring-boot:run
    networks:
      - microservices-network

  api-gateway:
    image: matheusslr/api-gateway:0.0.1
    ports:
      - "8765:8765"
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://discovery-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    command: mvn spring-boot:run
    depends_on:
      - discovery-server
      - rabbit-mq
    networks:
      - microservices-network

  cambio-service:
    image: matheusslr/cambio-service:0.0.1
    ports:
      - "8000:8000"
    command: mvn spring-boot:run
    restart: always
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING.DATASOURCE.URL: jdbc:mysql://db-cambio:3306/cambio_service?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.URL: jdbc:mysql://db-cambio:3306/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    depends_on:
      - discovery-server
      - db-cambio
      - rabbit-mq
    networks:
      - microservices-network

  book-service:
    image: matheusslr/book-service:0.0.1
    ports:
      - "8100:8100"
    command: mvn spring-boot:run
    restart: always
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://discovery-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin:9411/
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING.DATASOURCE.URL: jdbc:mysql://db-book:3307/book_service?useSSL=false&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.URL: jdbc:mysql://db-book:3307/book_service?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      SPRING.FLYWAY.PASSWORD: root
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    depends_on:
      - discovery-server
      - db-book
      - cambio-service
      - rabbit-mq
    networks:
      - microservices-network

volumes:
  cambio_service:
  book_service:

networks:
  microservices-network:
    driver: bridge