server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 2
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2       # Só é possível fazer duas requisições a cada 10s
        limitRefreshPeriod: 10s
  retry:
    instances:
      foo-bar:
        maxAttempts: 5
        waitDuration: 1s

spring:
  application:
    name: book-service
  config:
    import: file:03_book-service/env.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/book-service?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    flyway:
      url: jdbc:mysql://localhost:3307/
      schemas: book_service
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
springdoc:
  api-docs:
    path: book-service/v3/api-docs