server:
  port: 8888
spring:
  config:
    import: file:env.yaml
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/matheusslr/spring-config-server
          username: matheusslr
          password: ${GIT_PASSWORD}
          default-label: main
          search-paths:
            - 'greeting-service*'